package main

import "encoding/xml"

type AutoGenerated struct {
	MaterialMovementRequests []struct {
		ID                           int       `json:"id"`
		StateID                      int       `json:"stateId"`
		ExternalID                   int       `json:"externalId"`
		SenderEmployeeAccountLogin   string    `json:"senderEmployeeAccountLogin"`
		ReceiverEmployeeAccountLogin string    `json:"receiverEmployeeAccountLogin"`
		SenderStockID                int       `json:"senderStockId"`
		ReceiverStockID              int       `json:"receiverStockId"`
		CreateUser                   string    `json:"createUser"`
		CreateDate                   string    `json:"createDate"`
		RejectReasonID               string    `json:"rejectReasonId"`
		Note                         string    `json:"note"`
		Materials                    materials `json:"materials"`
	} `json:"materialMovementRequests"`
}

type materials []struct {
	MaterialInStockID        int    `json:"materialInStockId"`
	ProjectMask              string `json:"projectMask"`
	MaterialID               int    `json:"materialId"`
	MaterialExternalID       int    `json:"materialExternalId"`
	MaterialName             string `json:"materialName"`
	MaterialExternalUnitCode string `json:"materialExternalUnitCode"`
	Volume                   int    `json:"volume"`
}
type Users struct {
	XMLName xml.Name `xml:"Envelope"`
	Body    Body     `xml:"Body"`
}

type Body struct {
	XMLName xml.Name `xml:"Body"`
	GetList GetList  `xml:"GetList"`
	Get     Get      `xml:"Get"`
}

type GetList struct {
	XMLName xml.Name `xml:"GetList"`
	Id2     string   `xml:"Stock_ID_Receiver"`
}

type Get struct {
	XMLName xml.Name `xml:"Get"`
	Id2     string   `xml:"Request_ID"`
}

type StockStruct struct {
	Stocks []stock `json:"stocks"`
	Job    []stock `json:"job"`
}
type stock struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}
